name: Fabric
version: "2.0.0"

caliper:
    blockchain: fabric


channels:
    

    - channelName: shard2 
      contracts:
      - id: VSIContract2


    - channelName: shard3 
      contracts:
      - id: VSIContract3



    - channelName: shard4  
      contracts:
      - id: VSIContract4






organizations:

    - mspid: Org1MSP
      peers:
      - peer0.org1.example.com
      certificateAuthorities:
      - ca.org1.example.com
      identities:
          certificates:
              - name: "admin1"
                admin: "true"
                clientPrivateKey:
                    path: "../ScaleSFL-main/test-network/organizations/peerOrganizations/org1.example.com/users/Admin@org1.example.com/msp/keystore/3612cf1d7312ad90361261d4c7740459acca5e1691d22970f59112360d69494b_sk"
                clientSignedCert:
                    path: "../ScaleSFL-main/test-network/organizations/peerOrganizations/org1.example.com/users/Admin@org1.example.com/msp/signcerts/cert.pem"
      connectionProfile:
          path: "../ScaleSFL-main/test-network/organizations/peerOrganizations/org1.example.com/connection-org1.yaml"
          discover: false

    - mspid: Org2MSP
      peers:
      - peer0.org2.example.com
      certificateAuthorities:
      - ca.org2.example.com
      identities:
          certificates:
              - name: "admin2"
                admin: "true"
                clientPrivateKey:
                    path: "../ScaleSFL-main/test-network/organizations/peerOrganizations/org2.example.com/users/Admin@org2.example.com/msp/keystore/a30b72eb129c27d7f92a20ccc7dadf68d4f2a70f89fcc37f58372d20ced53794_sk"
                clientSignedCert:
                    path: "../ScaleSFL-main/test-network/organizations/peerOrganizations/org2.example.com/users/Admin@org2.example.com/msp/signcerts/cert.pem"
      connectionProfile:
          path: "../ScaleSFL-main/test-network/organizations/peerOrganizations/org2.example.com/connection-org2.yaml"
          discover: false


    - mspid: Org3MSP
      peers:
      - peer0.org3.example.com
      certificateAuthorities:
      - ca.org3.example.com
      identities:
          certificates:
              - name: "admin3"
                admin: "true"
                clientPrivateKey:
                    path: "../ScaleSFL-main/test-network/organizations/peerOrganizations/org3.example.com/users/Admin@org3.example.com/msp/keystore/3dd0878ad87186934d6793a570aee397d97dcc2b8582c2787064cfa67b2b25b7_sk"
                clientSignedCert:
                    path: "../ScaleSFL-main/test-network/organizations/peerOrganizations/org3.example.com/users/Admin@org3.example.com/msp/signcerts/cert.pem"
      connectionProfile:
          path: "../ScaleSFL-main/test-network/organizations/peerOrganizations/org3.example.com/connection-org3.yaml"
          discover: false




    - mspid: Org4MSP
      peers:
      - peer0.org4.example.com
      certificateAuthorities:
      - ca.org4.example.com
      identities:
          certificates:
              - name: "admin4"
                admin: "true"
                clientPrivateKey:
                    path: "../ScaleSFL-main/test-network/organizations/peerOrganizations/org4.example.com/users/Admin@org4.example.com/msp/keystore/1143893c30ac1f770ea809822b3359d6a8b331f2c2126e635697d4091d77d24e_sk"
                clientSignedCert:
                    path: "../ScaleSFL-main/test-network/organizations/peerOrganizations/org4.example.com/users/Admin@org4.example.com/msp/signcerts/cert.pem"
      connectionProfile:
          path: "../ScaleSFL-main/test-network/organizations/peerOrganizations/org4.example.com/connection-org4.yaml"
          discover: false

    - mspid: Org5MSP
      peers:
      - peer0.org5.example.com
      certificateAuthorities:
      - ca.org5.example.com
      identities:
          certificates:
              - name: "admin5"
                admin: "true"
                clientPrivateKey:
                    path: "../ScaleSFL-main/test-network/organizations/peerOrganizations/org5.example.com/users/Admin@org5.example.com/msp/keystore/78e966cb5864697b5b6cc20589353f81528fdb4e4e04c5c4b23225b03989a401_sk"
                clientSignedCert:
                    path: "../ScaleSFL-main/test-network/organizations/peerOrganizations/org5.example.com/users/Admin@org5.example.com/msp/signcerts/cert.pem"
      connectionProfile:
          path: "../ScaleSFL-main/test-network/organizations/peerOrganizations/org5.example.com/connection-org5.yaml"
          discover: false


    - mspid: Org6MSP
      peers:
      - peer0.org6.example.com
      certificateAuthorities:
      - ca.org6.example.com
      identities:
          certificates:
              - name: "admin6"
                admin: "true"
                clientPrivateKey:
                    path: "../ScaleSFL-main/test-network/organizations/peerOrganizations/org6.example.com/users/Admin@org6.example.com/msp/keystore/b0655b76435c75b31708aa29585ea3f2104faf8afbbff5e435bb39ace4cfe050_sk"
                clientSignedCert:
                    path: "../ScaleSFL-main/test-network/organizations/peerOrganizations/org6.example.com/users/Admin@org6.example.com/msp/signcerts/cert.pem"
      connectionProfile:
          path: "../ScaleSFL-main/test-network/organizations/peerOrganizations/org6.example.com/connection-org6.yaml"
          discover: false

      
orderers:
    orderer.example.com:
        url: grpcs://localhost:7050
        grpcOptions:
            ssl-target-name-override: orderer.example.com
        tlsCACerts:
            path: "../ScaleSFL-main/test-network/organizations/ordererOrganizations/example.com/orderers/orderer.example.com/msp/tlscacerts/tlsca.example.com-cert.pem"




peers:
  peer0.org1.example.com:
    url: grpcs://localhost:7051
    grpcOptions:
      ssl-target-name-override: peer0.org1.example.com
      grpc.keepalive_time_ms: 600000
    tlsCACerts:
      path: "../ScaleSFL-main/test-network/organizations/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/tls/tlscacerts/tls-localhost-7054-ca-org1.pem"

  peer0.org2.example.com:
    url: grpcs://localhost:9051
    grpcOptions:
      ssl-target-name-override: peer0.org2.example.com
      grpc.keepalive_time_ms: 600000
    tlsCACerts:
      path: "../ScaleSFL-main/test-network/organizations/peerOrganizations/org2.example.com/peers/peer0.org2.example.com/tls/tlscacerts/tls-localhost-8054-ca-org2.pem"

  peer0.org3.example.com:
    url: grpcs://localhost:11051
    grpcOptions:
      ssl-target-name-override: peer0.org3.example.com
      grpc.keepalive_time_ms: 600000
    tlsCACerts:
      path: "../ScaleSFL-main/test-network/organizations/peerOrganizations/org3.example.com/peers/peer0.org3.example.com/tls/tlscacerts/tls-localhost-11054-ca-org3.pem"




